### ISSUE TITLE
the operator add and sub is confused with sign of the number

### ISSUE THREAD

**Issue by RUEEE** [thpatch/thtk#69] opened 2020-02-03 07:24 UTC
(thtk12)
int A=1+ 2- 3;(it's ok)
int B=1--2; ("--" is ins_78 instead of "- -")
int C=1+2-3-4;("+" and "-" is not operator but sign)
int D=1++2+-3-+4;(it's ok)
better fix it maybe(though I've been used to it)

*迷惑行为*

by the way can it translate "[-9982]=x;return;" to "return x;"?(
by the road is there a sample of the function of thtk12((

**Comment by ManDude** [comment] 2020-02-03 23:44
Caused by allowing + and - on the left side of a number, and flex will always grab the largest token. Can be fixed by using more states. Fix ETA unknown.

**Closed** 2020-02-26 19:48 UTC
